"""empty message

Revision ID: 2843169a2c42
Revises: 7816fbc5e978
Create Date: 2017-11-13 23:03:45.480342

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2843169a2c42'
down_revision = '7816fbc5e978'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('order_user_id_fkey', 'order', type_='foreignkey')
    op.create_foreign_key(None, 'order', 'user', ['user_id'], ['id'], ondelete='RESTRICT')
    op.drop_constraint('order_details_order_id_fkey', 'order_details', type_='foreignkey')
    op.create_foreign_key(None, 'order_details', 'order', ['order_id'], ['id'], ondelete='RESTRICT')
    op.drop_constraint('order_temps_user_id_fkey', 'order_temps', type_='foreignkey')
    op.create_foreign_key(None, 'order_temps', 'user', ['user_id'], ['id'], ondelete='RESTRICT')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'order_temps', type_='foreignkey')
    op.create_foreign_key('order_temps_user_id_fkey', 'order_temps', 'user', ['user_id'], ['id'])
    op.drop_constraint(None, 'order_details', type_='foreignkey')
    op.create_foreign_key('order_details_order_id_fkey', 'order_details', 'order', ['order_id'], ['id'])
    op.drop_constraint(None, 'order', type_='foreignkey')
    op.create_foreign_key('order_user_id_fkey', 'order', 'user', ['user_id'], ['id'])
    # ### end Alembic commands ###
