"""empty message

Revision ID: 337906bc876c
Revises: d9ab0b08f761
Create Date: 2017-10-13 10:41:42.474037

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '337906bc876c'
down_revision = 'd9ab0b08f761'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user', 'coins',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user', 'coins',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
