"""empty message

Revision ID: 7816fbc5e978
Revises: f1775c2967b0
Create Date: 2017-11-09 15:09:29.397195

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7816fbc5e978'
down_revision = 'f1775c2967b0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_detail', sa.Column('fullname', sa.Text(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_detail', 'fullname')
    # ### end Alembic commands ###
