"""empty message

Revision ID: d9ab0b08f761
Revises: 
Create Date: 2017-10-13 10:22:12.122159

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'd9ab0b08f761'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('categorys')
    op.add_column('user', sa.Column('authenticated', sa.Boolean(), nullable=True))
    op.add_column('user', sa.Column('coins', sa.Integer(), nullable=False))
    op.add_column('user_detail', sa.Column('address', sa.Text(), nullable=False))
    op.add_column('user_detail', sa.Column('city', sa.Text(), nullable=False))
    op.add_column('user_detail', sa.Column('date_of_birth', sa.DateTime(), nullable=False))
    op.add_column('user_detail', sa.Column('district', sa.Text(), nullable=False))
    op.add_column('user_detail', sa.Column('gender', sa.Enum('0', '1', name='admin_role_enum'), nullable=False))
    op.add_column('user_detail', sa.Column('phone', sa.String(length=20), nullable=False))
    op.add_column('user_detail', sa.Column('ward', sa.Text(), nullable=False))
    op.drop_column('user_detail', 'quan_huyen')
    op.drop_column('user_detail', 'thanh_pho')
    op.drop_column('user_detail', 'gioi_tinh')
    op.drop_column('user_detail', 'phuong_xa')
    op.drop_column('user_detail', 'dia_chi_nhan')
    op.drop_column('user_detail', 'sdt')
    op.drop_column('user_detail', 'ngay_sinh')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_detail', sa.Column('ngay_sinh', postgresql.TIMESTAMP(), autoincrement=False, nullable=False))
    op.add_column('user_detail', sa.Column('sdt', sa.VARCHAR(length=20), autoincrement=False, nullable=False))
    op.add_column('user_detail', sa.Column('dia_chi_nhan', sa.TEXT(), autoincrement=False, nullable=False))
    op.add_column('user_detail', sa.Column('phuong_xa', sa.TEXT(), autoincrement=False, nullable=False))
    op.add_column('user_detail', sa.Column('gioi_tinh', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.add_column('user_detail', sa.Column('thanh_pho', sa.TEXT(), autoincrement=False, nullable=False))
    op.add_column('user_detail', sa.Column('quan_huyen', sa.TEXT(), autoincrement=False, nullable=False))
    op.drop_column('user_detail', 'ward')
    op.drop_column('user_detail', 'phone')
    op.drop_column('user_detail', 'gender')
    op.drop_column('user_detail', 'district')
    op.drop_column('user_detail', 'date_of_birth')
    op.drop_column('user_detail', 'city')
    op.drop_column('user_detail', 'address')
    op.drop_column('user', 'coins')
    op.drop_column('user', 'authenticated')
    op.create_table('categorys',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('date_created', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('date_modified', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('name', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('url', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='categorys_pkey'),
    sa.UniqueConstraint('name', name='categorys_name_key')
    )
    # ### end Alembic commands ###
