"""empty message

Revision ID: f7286219daed
Revises: 75b067bf4df2
Create Date: 2017-11-13 23:33:57.164339

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f7286219daed'
down_revision = '75b067bf4df2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('order_user_id_fkey', 'order', type_='foreignkey')
    op.create_foreign_key(None, 'order', 'user', ['user_id'], ['id'], onupdate='cascade', ondelete='cascade')
    op.drop_constraint('order_details_order_id_fkey', 'order_details', type_='foreignkey')
    op.create_foreign_key(None, 'order_details', 'order', ['order_id'], ['id'], onupdate='cascade', ondelete='cascade')
    op.drop_constraint('order_temps_user_id_fkey', 'order_temps', type_='foreignkey')
    op.create_foreign_key(None, 'order_temps', 'user', ['user_id'], ['id'], onupdate='cascade', ondelete='cascade')
    op.drop_constraint('products_category_id_fkey', 'products', type_='foreignkey')
    op.create_foreign_key(None, 'products', 'categories', ['category_id'], ['id'], ondelete='cascade')
    op.drop_constraint('user_detail_user_id_fkey', 'user_detail', type_='foreignkey')
    op.create_foreign_key(None, 'user_detail', 'user', ['user_id'], ['id'], ondelete='cascade')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user_detail', type_='foreignkey')
    op.create_foreign_key('user_detail_user_id_fkey', 'user_detail', 'user', ['user_id'], ['id'])
    op.drop_constraint(None, 'products', type_='foreignkey')
    op.create_foreign_key('products_category_id_fkey', 'products', 'categories', ['category_id'], ['id'])
    op.drop_constraint(None, 'order_temps', type_='foreignkey')
    op.create_foreign_key('order_temps_user_id_fkey', 'order_temps', 'user', ['user_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(None, 'order_details', type_='foreignkey')
    op.create_foreign_key('order_details_order_id_fkey', 'order_details', 'order', ['order_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(None, 'order', type_='foreignkey')
    op.create_foreign_key('order_user_id_fkey', 'order', 'user', ['user_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###
